import React from 'react';
import {createRoot} from 'react-dom/client';
createRoot(document.getElementById('root')).render(
<div style={{fontFamily:'Arial',padding:'40px'}}>
<h1>Explore IT Consulting</h1>
<p>Production website scaffold generated by ChatGPT.</p>
<p>Domain: exploreitconsulting.com</p>
</div>
);
